import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The library sidebar is auto-generated from the folder structure under docs/:
 *   docs/prompts/ · docs/skills/ · docs/workflows/  (folder = category)
 * Adding a new entry is just adding a markdown file — the sidebar updates itself.
 */
const sidebars: SidebarsConfig = {
  librarySidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
